opencost:
  customPricing:
    enabled: true
    provider: azure
    costModel:
      description: Modified pricing configuration.
      CPU: 0.031611
      spotCPU: 0.006655
      RAM: 0.004237
      spotRAM: 0.000892
      GPU: 0.95
      storage: 0.00005479452
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143
      spotLabel: ""
      spotLabelValue: ""
      projectID: "${ACCOUNT_ID}"
  exporter:
    defaultClusterId: opencost-new
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: warn #error
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret

  prometheus:
    internal:
      enabled: true
      serviceName: prometheus-server
      namespaceName: prometheus-system
  ui:
    enabled: true
extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key
